from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    INPUT_FILE_NOT_FOUND = "INPUT_FILE_NOT_FOUND"
    INPUT_UNSUPPORTED_FORMAT = "INPUT_UNSUPPORTED_FORMAT"
    INPUT_DECODE_FAILED = "INPUT_DECODE_FAILED"
    RECIPE_INVALID_TYPE = "RECIPE_INVALID_TYPE"
    RECIPE_PARAM_MISSING = "RECIPE_PARAM_MISSING"
    RECIPE_VERSION_UNSUPPORTED = "RECIPE_VERSION_UNSUPPORTED"
    EXEC_STEP_FAILED = "EXEC_STEP_FAILED"
    EXEC_GPU_INIT_FAILED = "EXEC_GPU_INIT_FAILED"
    EXEC_OUT_OF_MEMORY = "EXEC_OUT_OF_MEMORY"
    SAVE_PERMISSION_DENIED = "SAVE_PERMISSION_DENIED"
    SAVE_PATH_INVALID = "SAVE_PATH_INVALID"
    SETTINGS_LOAD_FAILED = "SETTINGS_LOAD_FAILED"
    BATCH_INVALID_OUTPUT_DIR = "BATCH_INVALID_OUTPUT_DIR"
